defmodule Skein.CLI.AgentsMd do
  @moduledoc """
  Generates and updates the `AGENTS.md` agent-context file in Skein projects.

  `AGENTS.md` is the cross-tool convention read automatically by coding
  agents (Claude Code, Codex, Cursor, ...). The generated content is a
  compact Skein language primer embedded into this module at build time
  from the docs site source (`reference/agent-primer.md`), so it tracks
  the installed toolchain version instead of drifting from the docs.

  The generated section lives between marker comments; everything outside
  the markers is user content and survives regeneration.
  """

  @start_marker "<!-- skein:generated:start -->"
  @end_marker "<!-- skein:generated:end -->"

  @primer_path Path.expand(
                 "../../../../../docs/site/src/content/docs/reference/agent-primer.md",
                 __DIR__
               )
  @external_resource @primer_path

  # Embed the primer body at compile time: everything from the first "##"
  # heading onward (drops the docs-site frontmatter and intro paragraph,
  # which describe the page rather than the language).
  @primer (fn raw ->
             case :binary.match(raw, "\n## ") do
               {pos, _len} ->
                 raw |> binary_part(pos + 1, byte_size(raw) - pos - 1) |> String.trim()

               :nomatch ->
                 raise "agent-primer.md has no '## ' section headings"
             end
           end).(File.read!(@primer_path))

  @doc """
  The embedded language primer body (markerless).

  Also the generation context of the agent-writability benchmark
  (`Skein.CLI.Bench`), so the benchmark measures writing Skein from
  exactly the context every scaffolded project hands its agents.
  """
  @spec primer() :: String.t()
  def primer, do: @primer

  @doc "The start marker delimiting the generated block."
  @spec start_marker() :: String.t()
  def start_marker, do: @start_marker

  @doc "The end marker delimiting the generated block."
  @spec end_marker() :: String.t()
  def end_marker, do: @end_marker

  @doc """
  Renders the generated block (markers included) for the current toolchain.

  Deterministic for a given toolchain version, which makes regeneration
  idempotent.
  """
  @spec generated_block() :: String.t()
  def generated_block do
    """
    #{@start_marker}
    <!-- Generated by `skein agents` (skein #{version()}). Do not edit inside this block: -->
    <!-- it is overwritten on regeneration. Add project-specific notes outside the markers. -->

    # Working in a Skein Project

    #{@primer}

    #{@end_marker}
    """
    |> String.trim_trailing()
  end

  @doc """
  Renders the content of a fresh `AGENTS.md` (generated block plus an
  empty user section below the markers).
  """
  @spec render() :: String.t()
  def render do
    generated_block() <> "\n\n<!-- Project-specific guidance goes below this line. -->\n"
  end

  @doc """
  Creates `AGENTS.md` in `project_dir`, or updates only the generated
  block of an existing one. Content outside the markers is preserved.
  A file without markers gets the generated block appended.

  Returns `{:ok, %{path: path, action: :created | :updated}}`.
  """
  @spec upsert(String.t()) :: {:ok, %{path: String.t(), action: :created | :updated}}
  def upsert(project_dir) do
    path = Path.join(project_dir, "AGENTS.md")

    case File.read(path) do
      {:error, :enoent} ->
        File.write!(path, render())
        {:ok, %{path: path, action: :created}}

      {:ok, existing} ->
        File.write!(path, replace_generated_block(existing))
        {:ok, %{path: path, action: :updated}}
    end
  end

  @doc """
  Replaces the generated block within `content`, preserving everything
  outside the markers. Appends the block if no markers are present.
  """
  @spec replace_generated_block(String.t()) :: String.t()
  def replace_generated_block(content) do
    with {start_pos, _} <- :binary.match(content, @start_marker),
         {end_pos, end_len} <- :binary.match(content, @end_marker) do
      if end_pos >= start_pos do
        before = binary_part(content, 0, start_pos)
        rest_start = end_pos + end_len
        rest = binary_part(content, rest_start, byte_size(content) - rest_start)
        before <> generated_block() <> rest
      else
        append_generated_block(content)
      end
    else
      :nomatch -> append_generated_block(content)
    end
  end

  defp append_generated_block(content) do
    String.trim_trailing(content) <> "\n\n" <> generated_block() <> "\n"
  end

  @doc "Content for the one-line `CLAUDE.md` pointer file."
  @spec claude_md_pointer() :: String.t()
  def claude_md_pointer, do: "See AGENTS.md.\n"

  defp version do
    case Application.spec(:skein_cli, :vsn) do
      nil -> "dev"
      vsn -> to_string(vsn)
    end
  end
end
