defmodule Skein.CLI.CompletionsTest do
  @moduledoc """
  zsh tab-completion for skein (issue #101): the completion script is
  generated by `skein completions zsh` and must cover every subcommand
  the help text lists — completions can't silently drift from the real
  command surface.
  """
  use ExUnit.Case, async: true

  alias Skein.CLI

  test "completions zsh returns a zsh completion script" do
    assert {:ok, script} = CLI.completions(["zsh"])
    assert script =~ "#compdef skein"
    assert script =~ "_skein"
  end

  test "every subcommand in the help text appears in the completion script" do
    {:ok, script} = CLI.completions(["zsh"])
    usage = Skein.CLI.Main.usage_text()

    commands =
      Regex.scan(~r/^  (\w[\w-]*)\b/m, usage)
      |> Enum.map(fn [_, command] -> command end)
      |> Enum.uniq()

    assert commands != []

    for command <- commands do
      assert script =~ command,
             "subcommand '#{command}' from skein help is missing from the zsh completions"
    end
  end

  test "per-command flags are completed" do
    {:ok, script} = CLI.completions(["zsh"])
    assert script =~ "--output"
    assert script =~ "--port"
    assert script =~ "--last"
    assert script =~ "--kind"
    assert script =~ "--no-agents"
    assert script =~ "--no-git"
    assert script =~ "--backend"
  end

  test "new --backend offers the recognized llm backends" do
    {:ok, script} = CLI.completions(["zsh"])
    assert script =~ "anthropic bedrock openai_compatible test"
  end

  test "compile completes .skein files and trace --kind offers span kinds" do
    {:ok, script} = CLI.completions(["zsh"])
    assert script =~ "*.skein"
    assert script =~ "http llm tool"
  end

  test "unsupported shells are a structured error" do
    assert {:error, message} = CLI.completions(["fish"])
    assert message =~ "zsh"
  end

  test "missing shell argument is a usage error" do
    assert {:error, message} = CLI.completions([])
    assert message =~ "Usage"
  end
end
