defmodule Skein.Runtime.Request do
  @moduledoc """
  Runtime request body parsing and validation for Skein handlers.

  Provides `req.json[T]` functionality — parses a request's JSON body
  and validates it against a JSON Schema derived from a Skein type declaration.

  ## Usage

  Called by compiled handler code:

      # In generated Core Erlang, req.json[UserInput] compiles to:
      Skein.Runtime.Request.json(req_map, schema)

  Returns `{:ok, parsed_map}` or `{:error, reason}`.
  """

  @doc """
  Parses the request body as JSON and validates against the given schema.

  The `req` map must contain a `:body` key with a JSON string.
  The `schema` is a JSON Schema map (as generated by `Skein.CodeGen.SchemaGen`).

  Returns `{:ok, parsed}` on success or `{:error, reason}` on failure.
  """
  @spec json(map(), map()) :: {:ok, map()} | {:error, String.t()}
  def json(req, schema) when is_map(req) and is_map(schema) do
    body = Map.get(req, :body, "")

    case Jason.decode(body) do
      {:ok, parsed} when is_map(parsed) ->
        validate(parsed, schema)

      {:ok, _non_map} ->
        {:error, "Invalid JSON: expected object, got non-object value"}

      {:error, _decode_error} ->
        {:error, "Invalid JSON: could not parse request body"}
    end
  end

  # ------------------------------------------------------------------
  # Schema validation
  # ------------------------------------------------------------------

  defp validate(parsed, schema) when map_size(schema) == 0 do
    # Empty schema = no validation
    {:ok, parsed}
  end

  defp validate(parsed, schema) do
    with :ok <- validate_required(parsed, schema),
         :ok <- validate_types(parsed, schema) do
      {:ok, parsed}
    end
  end

  defp validate_required(parsed, schema) do
    required = Map.get(schema, "required", [])

    missing =
      Enum.reject(required, fn field ->
        Map.has_key?(parsed, field)
      end)

    case missing do
      [] -> :ok
      fields -> {:error, "Missing required fields: #{Enum.join(fields, ", ")}"}
    end
  end

  defp validate_types(parsed, schema) do
    properties = Map.get(schema, "properties", %{})

    errors =
      Enum.reduce(properties, [], fn {field, field_schema}, acc ->
        case Map.get(parsed, field) do
          nil ->
            # Field not present — already handled by required check
            acc

          value ->
            case validate_type(value, field_schema) do
              :ok -> acc
              {:error, reason} -> ["#{field}: #{reason}" | acc]
            end
        end
      end)

    case errors do
      [] -> :ok
      errs -> {:error, "Validation failed: #{Enum.join(Enum.reverse(errs), "; ")}"}
    end
  end

  defp validate_type(value, %{"type" => "string"}) when is_binary(value), do: :ok
  defp validate_type(_value, %{"type" => "string"}), do: {:error, "expected string"}

  defp validate_type(value, %{"type" => "integer"}) when is_integer(value), do: :ok
  defp validate_type(_value, %{"type" => "integer"}), do: {:error, "expected integer"}

  defp validate_type(value, %{"type" => "number"}) when is_number(value), do: :ok
  defp validate_type(_value, %{"type" => "number"}), do: {:error, "expected number"}

  defp validate_type(value, %{"type" => "boolean"}) when is_boolean(value), do: :ok
  defp validate_type(_value, %{"type" => "boolean"}), do: {:error, "expected boolean"}

  defp validate_type(value, %{"type" => "array"}) when is_list(value), do: :ok
  defp validate_type(_value, %{"type" => "array"}), do: {:error, "expected array"}

  defp validate_type(value, %{"type" => "object"}) when is_map(value), do: :ok
  defp validate_type(_value, %{"type" => "object"}), do: {:error, "expected object"}

  # No type specified — always valid
  defp validate_type(_value, _schema), do: :ok
end
