defmodule Skein.Runtime.Request do
  @moduledoc """
  Runtime request body parsing and validation for Skein handlers.

  Provides `req.json[T]` functionality — parses a request's JSON body
  and validates it against a JSON Schema derived from a Skein type declaration.

  ## Usage

  Called by compiled handler code:

      # In generated Core Erlang, req.json[UserInput] compiles to:
      Skein.Runtime.Request.json(req_map, schema)

  Returns `{:ok, parsed_map}` or `{:error, reason}`.
  """

  alias Skein.Runtime.ValidationError

  @doc """
  Parses the request body as JSON and validates against the given schema.

  The `req` map must contain a `:body` key with a JSON string.
  The `schema` is a JSON Schema map (as generated by `Skein.CodeGen.SchemaGen`).

  Returns `{:ok, parsed}` on success or `{:error, reason}` on failure.
  """
  @spec json(map(), map()) ::
          {:ok, map()} | {:error, Skein.Runtime.ValidationError.t() | String.t()}
  def json(req, schema) when is_map(req) and is_map(schema) do
    body = Map.get(req, :body, "")

    case Jason.decode(body) do
      {:ok, parsed} when is_map(parsed) ->
        validate(parsed, schema)

      {:ok, _non_map} ->
        {:error, ValidationError.new(["request body must be a JSON object"])}

      {:error, _decode_error} ->
        {:error, ValidationError.new(["request body is not valid JSON"])}
    end
  end

  # ------------------------------------------------------------------
  # Schema validation
  # ------------------------------------------------------------------

  # One recursive schema engine (C3/#298): `Skein.Runtime.JsonSchema`
  # validates the full nested shape (required/types/constraints/formats/
  # uniqueItems, recursively) and atomizes schema-declared keys (Option
  # fields become Some/None) so compiled field access lands on atom keys —
  # the same engine the llm.json[T] and tool input/output paths use.
  defp validate(parsed, schema) do
    case Skein.Runtime.JsonSchema.decode(parsed, schema) do
      {:ok, decoded} -> {:ok, decoded}
      {:error, violations} -> {:error, ValidationError.new(violations)}
    end
  end
end
